name: Evaluate GitHub Repos
on: workflow_dispatch
env:
  SPREADSHEET_URL: ${{ vars.SPREADSHEET_URL }}
  TEMPDIR: "/tmp"
jobs:
  check-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run checks
        run: python github_evaluation.py
      - name: Upload evaluation results
        uses: actions/upload-artifact@v4
        with:
          name: evaluation_results.csv
          path: evaluation_results.csv